"""add_academic_year_id_to_student_fees_and_aadhar_last4

Revision ID: 384df2f48f9d
Revises: None
Create Date: 2026-04-11
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '384df2f48f9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_fees', sa.Column('academic_year_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student_fees', 'academic_years', ['academic_year_id'], ['id'])
    op.add_column('students', sa.Column('aadhar_last4', sa.String(length=4), nullable=True))
    op.drop_column('students', 'aadhar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('aadhar', sa.VARCHAR(length=12), nullable=True))
    op.drop_column('students', 'aadhar_last4')
    op.drop_constraint(None, 'student_fees', type_='foreignkey')
    op.drop_column('student_fees', 'academic_year_id')
    # ### end Alembic commands ###